inertia:
  m: 225 # Weight of the Vehicle [kg]
  g: 9.81 # Gravity force         [m/s^2]
  I_z: 31.27 # Inertial force I_zz   [kg/m^2]
  Cf: 898.1 # N/rad Front tire cornering stiffness
  Cr: 1097.6 # N/rad Rear tire cornering stiffness

kinematics:
  l: 1.58 # Wheelbase              [m]
  b_F: 0.869 # From COG to front axle [m]
  b_R: 0.711 # From COG to rear axle  [m]
  w_front: 0.45 # Percentage of weight front
  axle_width: 1.4

tire:
  tire_coefficient: 1.0
  B: 0.70
  C: 1.3
  D: 1.0
  E: -1.6
  radius: 0.2525

aero:
  C_Down: 1.9 # F_Downforce = C_Downforce*v_x^2
  C_drag: 1 # F_Drag = C_Drag*v_x^2

powertrain:
  motor_count: 2
  front_motor_count: 1
  rear_motor_count: 1
  enable_regen: true
  final_drive_ratio: 3.5
  gear_efficiency: 0.95
  drive_efficiency: 0.92
  regen_efficiency: 0.70
  max_power_kw: 17.0
  max_regen_kw: 17.0
  torque_split_front: 1.0
  torque_split_rear: 1.0
  torque_front_max_nm: 195.0
  torque_rear_max_nm: 195.0
  drive_curve:
    rpm: [0, 1000, 3000, 4000, 4500]
    torque: [55.7, 55.7, 55.7, 40.6, 0.0]
  regen_curve:
    rpm: [0, 1000, 3000, 4000, 4500]
    torque: [27.2, 27.2, 27.2, 20.0, 0.0]
  battery:
    capacity_kwh: 5.1
    soc_init: 0.9
    soc_min: 0.1
    soc_max: 0.95
    soc_torque_fade_start: 0.2
    soc_regen_fade_start: 0.9
    nominal_voltage: 51.2

brakes:
  front_bias: 0.58
  rear_bias: 0.42
  max_force: 8000.0
  regen_fraction: 0.6
  min_regen_speed: 1.0

input_ranges:
  acceleration:
    max: 1.0
    min: -1.0
  velocity:
    max: 30.1964649875
    min: 0
  steering:
    max: 0.3665191
    min: -0.3665191

physics:
  h_cg: 0.25       # m
  c_rr: 0.012      # rolling resistance coefficient
  tau_throttle: 0.06   # s (actuator time constant)
  tau_brake: 0.03      # s

